POST http://localhost:5271/musics
Content-Type: application/json

{
    "name" : "",
    "author" : "",
    "genres" : [
        "Eletronic",
        "Future Base",
        "EDM"
    ],
    "createdDateTime" : "2019-04-08T08:00:00"

}

###

GET http://localhost:5271/Musics/64786481-f7ba-4815-a125-44112a2ea2be

###

@id=64786481-f7ba-4815-a125-44112a2ea2be
PUT http://localhost:5271/musics/{{id}}
Content-Type: application/json

{
    "name" : "Sunburn",
    "author" : "DROELOE",
    "genres" : [
        "Eletronic",
        "Future Base",
        "EDM"
    ],
    "createdDateTime" : "2019-04-08T08:00:00"

}
###

@id=64786481-f7ba-4815-a125-44112a2ea2be
DELETE http://localhost:5271/musics/{{id}}

###
@id=64786481-f7ba-4815-a125-44112a2ea2be
GET http://localhost:5271/musics/{{id}}